version: "3"

networks:
  monitoring:
    driver: bridge
  es:
    external:
      name: elastic

volumes:
  prometheus_data: {}
  grafana_plugins: {}

services:
  otelcol:
    image: otel/opentelemetry-collector-contrib:0.46.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otelcol.yaml:/etc/otel-collector-config.yaml
      - ./testdata:/testdata
    ports:
      - "4317:4317"          # OTLP gRPC receiver
    environment:
       - ELASTIC_ENDPOINT=${ELASTIC_ENDPOINT}
       - ELASTIC_INDEX=${ELASTIC_INDEX}
       - ELASTIC_USER=elastic
       - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    networks:
      - monitoring
      - es

  prometheus:
    image: prom/prometheus:latest
    #container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-remote-write-receiver'
    ports:
      - "9090:9090"
    networks:
      - monitoring


  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
      - grafana_plugins:/var/lib/grafana/plugins
    environment:
      - PROM_ENDPOINT=http://prometheus:9090
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      - monitoring
      - es
