receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:

  elasticsearch:
    endpoints: [ "${ELASTIC_ENDPOINT}" ]
    index: "${ELASTIC_INDEX}"
    user: "${ELASTIC_USER}"
    password: "${ELASTIC_PASSWORD}"
    discover:
      on_start: true
    flush:
      bytes: 10485760
    retry:
      max_requests: 5

  filelog:
  filelog/nginx:
    include: [ "/testdata/nginx-access.log" ]
    #start_at: beginning
    operators:
      - type: regex_parser
        #127.0.0.1 - - [04/Jul/2021:21:03:19 +0800] "GET /favicon-32x32.png HTTP/1.1" 200 628 "http://api.local/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
        regex: '^(?P<remote_addr>[^\s]+) - (?P<remote_user>[^\s]+) \[(?P<time_local>[^\]]+)\] \"(?P<request>[^\"]+)\" (?P<status>\d+) (?P<body_bytes_sent>\d+) \"(?P<http_referer>[^\"]+)\" \"(?P<http_user_agent>[^\"]+)\"$'
        timestamp:
          parse_from: time_local
          layout_type: gotime
          layout: "02/Jan/2006:15:04:05 -0700"
      - type: add
        field: "type"
        value: "nginx"

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, elasticsearch]
