kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  "APISelfSubjectReview": true
runtimeConfig:
  "authentication.k8s.io/v1alpha1": "true"
nodes:
- role: control-plane
  kubeadmConfigPatches:
    - |
      apiVersion: kubeadm.k8s.io/v1beta3
      kind: ClusterConfiguration
      apiServer:
        extraArgs:
          enable-aggregator-routing: "true"
          #feature-gates: "ValidatingAdmissionPolicy=true"
